### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by manaswinidas**
Fix typos in README and Projects page

### CODE REVIEW

**Review by shivaylamba — APPROVED** [review]

**Comment by shivaylamba** [comment]
@manaswinidas you will need to resolve the merge conflicts.

**Comment by manaswinidas** [comment]
@shivaylamba resolved conflicts. Looks like all typos have been fixed in the previous commits.

**Comment by ksraj123** [comment]
Thanks @manaswinidas

**Comment by ksraj123** [comment]
@manaswinidas Could you please squash your commits. Thanks

**Pull request merged**
