### PR TITLE
Improves UI of the website by proper spacing and fixing Nav.

### PR DESCRIPTION
**Pull request by rak-shit**
Nav Collapse Before

The above image is of Nav in mobile view before the edit

Nav Collapse After

The above image is of Nav in mobile view after the edit

There were some extra spaces which are being fixed There were also some views where the spacing was too less.

### CODE REVIEW

**Comment by ayushnagar123** [comment]
Please center the drop-down if possible and updtae the pr.

**Comment by rak-shit** [comment]
> Please center the drop-down if possible and updtae the pr.

Okay. Will do.

**Comment by rak-shit** [comment]
Screenshot 2020-01-30 at 12 40 44 PM

Updated drop-down

**Comment by ayushnagar123** [comment]
Great work @rak-shit

**Pull request merged**
